command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port"
  - "8501"
  - "--server.headless"
  - "true"

env:
  - name: DATABRICKS_HOST
    valueFrom: "context"
  - name: DATABRICKS_TOKEN
    valueFrom: "context"
